### ISSUE TITLE
Простой скрипт для генерации плейлистов

### ISSUE THREAD

**Issue by Noxoomo** [cscenter/automatic-playlist-generation#5]
Входные данные: прядущая песня, веса всех остальных документов из коллекции
Выход: случайная песня, выбранная с вероятностью, пропорциональной входному весу

**Comment by korskovan** [comment]
Совсем-совсем простой и в итоге не использовался
https://github.com/cscenter/automatic-playlist-generation/blob/master/Generators/simple.py
