### ISSUE TITLE
Сбор датасета

### ISSUE THREAD

**Issue by Noxoomo** [cscenter/automatic-playlist-generation#6]
Хотим автоматически собирать датасет для обучения:
Формат следующий (tsv):
playlist_id position_in_playlist song song_features_and_meta

**Comment by korskovan** [comment]
Формат получился не такой для удобства хранения и обработки, подробнее https://github.com/cscenter/automatic-playlist-generation/wiki/%D0%A1%D0%B1%D0%BE%D1%80-%D0%B4%D0%B0%D1%82%D0%B0%D1%81%D0%B5%D1%82%D0%B0
